package com.xt.notes.common.utils

object MainDestinations {
    const val HOME_ROUTE = "home"
    const val NETFCHILL_MOVIE_DETAIL_ROUTE = "movie"
    const val NETFCHILL_TV_SHOW_DETAIL_ROUTE = "tv_show"
    const val NETFCHILL_ID_KEY = "NETFCHILLId"
    const val NETFCHILL_TRENDING_MOVIES_ROUTE = "trending_movies"
    const val NETFCHILL_POPULAR_MOVIES_ROUTE = "popular_movies"
    const val NETFCHILL_NOW_PLAYING_MOVIES_ROUTE = "now_playing_movies"
    const val NETFCHILL_UPCOMING_MOVIES_ROUTE = "upcoming_movies"
    const val NETFCHILL_TOP_RATED_MOVIES_ROUTE = "top_rated_movies"
    const val NETFCHILL_DISCOVER_MOVIES_ROUTE = "discover_movies"
    const val NETFCHILL_SEARCH_MOVIE_ROUTE = "search_movies"
    const val NETFCHILL_TRENDING_TV_SHOW_ROUTE = "trending_tv_show"
    const val NETFCHILL_POPULAR_TV_SHOW_ROUTE = "popular_tv_show"
    const val NETFCHILL_AIRING_TODAY_TV_SHOW_ROUTE = "airing_today_tv_show"
    const val NETFCHILL_ON_THE_AIR_TV_SHOW_ROUTE = "on_the_air_tv_show"
    const val NETFCHILL_TOP_RATED_TV_SHOW_ROUTE = "top_rated_tv_show"
    const val NETFCHILL_DISCOVER_TV_SHOW_ROUTE = "discover_tv_show"
    const val NETFCHILL_SEARCH_TV_SHOW_ROUTE = "search_tv_show"
    const val NETFCHILL_CAST_ROUTE = "cast_list"
    const val NETFCHILL_CREW_ROUTE = "crew_list"
    const val NETFCHILL_CREDIT_KEY =  "credit_list"
    const val NETFCHILL_PERSON_ROUTE = "person"
    const val NETFCHILL_PERSON_KEY = "personId"
}
